if( ! eap_data ) eap_data = {};

eap_data.examples = {

  a: {"cells":[{"title":"((post_title))","content":"((excerpt | 30)) ((link | more))","type":"Featured Image","image":"Large","templateHelp":1,"$$hashKey":"object:3"},{"title":"((post_title | max_length: 25 | append:...))","content":"((excerpt | max_length: 135 | append:...))((link | text: know more))","type":"Regular","image":"Full","templateHelp":1,"$$hashKey":"object:4"},{"title":"Origin Story","content":"((meta_key | key: eap-origin-story | max_length: 150 | append:...))((link | text: know more))","type":"Regular","image":"Full","templateHelp":1,"$$hashKey":"object:5"},{"title":"Super Power","content":"((meta_key | key: eap-super-power | max_length: 150 | append:...))((link | text: know more))","type":"Regular","image":"Full","templateHelp":1,"$$hashKey":"object:62"},{"title":"Weakness","content":"((meta_key | key: eap-weakness | max_length: 150 | append:...))((link | text: know more))","type":"Regular","image":"Full","templateHelp":1,"$$hashKey":"object:70"}],"resp":{"flex":[3,3,1],"fixed":[300,300],"image_height":[300,300,200],"flex_or_fixed":"flex"},"query":{"posts_per_page":10,"query_vars":""},"database":{"post_type":{"post":{"use":true,"taxonomy":{"category":{"use":true,"terms":{"6":{"use":true}}}}}}}},

  b: {"cells":[{"title":"((post_title))","content":"((excerpt | 30)) ((link | more))","type":"Featured Image","image":"Full","templateHelp":1},{"title":"((post_title | max_length: 20 | append:...))","content":"((excerpt | max_length: 200 | append:...))((link | text: know more))","type":"Regular","image":"Full","templateHelp":1,"pre_open":false}],"resp":{"flex":[2,2,1],"fixed":[300,300],"image_height":[300,300,200],"flex_or_fixed":"flex"},"query":{"posts_per_page":10,"query_vars":""},"database":{"post_type":{"post":{"use":true,"taxonomy":{"category":{"use":true,"terms":{"6":{"use":true}}}}}}}},

  c: {"cells":[{"title":"((post_title | max_length: 25 | append:...))","content":"((excerpt | max_length: 300 | append:...))((link | text: know more))","type":"Regular","image":"Full","templateHelp":1}],"resp":{"flex":[1,1,1],"fixed":[300,300],"image_height":[300,300,200],"flex_or_fixed":"flex"},"query":{"posts_per_page":10,"query_vars":""},"database":{"post_type":{"post":{"use":true,"taxonomy":{"category":{"use":true,"terms":{"6":{"use":true}}}}}}}},

  d: {"cells":[{"title":"((post_title))","content":"((excerpt | 30)) ((link | more))","type":"Featured Image","image":"Full","templateHelp":1},{"title":"((post_title | max_length: 20 | append:...))","content":"((excerpt | max_length: 135 | append:...))((link | text: know more))","type":"Regular","image":"Full","templateHelp":1,"pre_open":true},{"title":"Origin Story","content":"((meta_key | key: eap-origin-story | max_length: 150 | append:...))((link | text: know more))","type":"Regular","image":"Full","templateHelp":1}],"resp":{"flex":[3,3,1],"fixed":[300,300],"image_height":[300,300,200],"flex_or_fixed":"flex"},"query":{"posts_per_page":10,"query_vars":""},"database":{"post_type":{"post":{"use":true,"taxonomy":{"category":{"use":true,"terms":{"6":{"use":true}}}}}}}},

  e: {"cells":[{"title":"((post_title))","content":"((excerpt | 30)) ((link | more))","type":"Featured Image","image":"Full","templateHelp":1},{"title":"((post_title | max_length: 25 | append:...))","content":"","type":"Regular","image":"Full","templateHelp":1},{"title":"Origin Story","content":"((meta_key | key: eap-origin-story | max_length: 500 | append:...))","type":"Regular","image":"Full","templateHelp":1},{"title":"","content":"<b style=\"width: 66%; display: inline-block;\">Lorem: </b><span style=\"width: 33%; display: inline-block; text-align: right\">((meta_key | key: eap-lorem))</span>","type":"Regular","image":"Full","templateHelp":1},{"title":"","content":"<b style=\"width: 66%; display: inline-block;\">Ipsum: </b><span style=\"width: 33%; display: inline-block; text-align: right\">((meta_key | key: eap-ipsum))</span>","type":"Regular","image":"Full","templateHelp":1},{"title":"","content":"<b style=\"width: 66%; display: inline-block;\">Dolor: </b><span style=\"width: 33%; display: inline-block; text-align: right\">((meta_key | key: eap-dolor))</span>","type":"Regular","image":"Full","templateHelp":1},{"title":"((link | text: Know More))","content":"","type":"Regular","image":"Full","templateHelp":1}],"resp":{"flex":[3,3,1],"fixed":[300,300],"image_height":[300,300,200],"flex_or_fixed":"flex"},"query":{"posts_per_page":10,"query_vars":""},"database":{"post_type":{"post":{"use":true,"taxonomy":{"category":{"use":true,"terms":{"6":{"use":true}}}}}}}},

  f: {"cells":[{"title":"((post_title | max_length: 20 | append:...))","content":"((featured_image | size: Medium))((excerpt | max_length: 135 | append:...))((link | text: know more))\n&#60;div style=&quot;margin-top: 10px;&quot;&#62;\n&#60;b&#62;Lorem: &#60;/b&#62;\n((meta_key | key: eap-lorem | max_length: 50 | append:...))\n&#60;/div&#62;\n&#60;div style=&quot;margin-top: 10px;&quot;&#62;\n&#60;b&#62;Ipsum: &#60;/b&#62;\n((meta_key | key: eap-ipsum | max_length: 50 | append:...))\n&#60;/div&#62;\n&#60;div style=&quot;margin-top: 10px;&quot;&#62;\n&#60;b&#62;Dolor: &#60;/b&#62;\n((meta_key | key: eap-dolor| max_length: 50 | append:...))\n&#60;/div&#62;","type":"Regular","image":"Full","templateHelp":1}],"resp":{"flex":[3,3,1],"fixed":[300,300],"image_height":[300,300,200],"flex_or_fixed":"flex"},"query":{"posts_per_page":10,"query_vars":""},"database":{"post_type":{"post":{"use":true,"taxonomy":{"category":{"use":true,"terms":{"6":{"use":true}}}}}}}}

};
